### ISSUE TITLE
Copy/paste bug in buildParameters() method for AndCriteria, OrCriteria, etc.

### ISSUE THREAD

**Issue by alexjlockwood** [reinaldoarrosi/QueryBuilder#3]
For example, in `OrCriteria.java` you do:

``` java
public List<Object> buildParameters() {
    List<Object> ret = new ArrayList<Object>();

    if(left != null)
        ret.addAll(left.buildParameters());

    if(right != null)
        ret.addAll(left.buildParameters());

    return ret;
}
```

I think for the second if statement you meant to pass in `right.buildParameters()` instead of `left.buildParameters()`:

``` java
if(right != null)
    ret.addAll(right.buildParameters());
```

I checked `AndCriteria.java` and the same issue was present... I didn't look at any other criteria but I'd double check if I were you.

**Comment by reinaldoarrosi** [comment]
Thanks for spotting it. 
I'll review all `buildParameters` methods and fix them if needed.
