### ISSUE TITLE
Add logic to publish release into maven central/jCenter

### ISSUE THREAD

**Issue by skrzyneckik** [reinaldoarrosi/QueryBuilder#6]
It should be relatively easy if we follow [this tutorial](https://inthecheesefactory.com/blog/how-to-upload-library-to-jcenter-maven-central-as-dependency/en)

**Comment by bogdanRada** [comment]
any updates on this? i would really like to use this library

**Comment by reinaldoarrosi** [comment]
Sorry for the super-slow progress on this issue. Finally got around to doing it.

Commit https://github.com/reinaldoarrosi/QueryBuilder/commit/cdd67bcb6cba6785fc72a57e7c30698f2a0f0da3 added the necessary logic to publish QueryBuilder as a package in jcenter/maven central. 

I'm now just waiting bintray to sync with jcenter and then it's done. 
I'll keep the issue open until this happens.

**Comment by bogdanRada** [comment]
Awesome 😊😊

**Comment by reinaldoarrosi** [comment]
Finally 😄 !!!
Install instructions were also updated.
